version: 2

build:
  os: ubuntu-22.04
  tools:
    python: "3.10"
  commands:
    - pip install poetry
    - poetry install --no-root --with docs
    - poetry run sphinx-build -b html docs/ docs/_build/html

sphinx:
  configuration: docs/conf.py